language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - pypy3

install:
  - python setup.py install
  - pip install coverage flake8

script:
  - coverage run --source=watchtower ./test/test.py
#  - coverage report --show-missing

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - python: pypy3

sudo: false
cache: pip
